version: "3"
services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/uploads

  db:
    image: "mysql:8.0"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: careers
      MYSQL_ROOT_PASSWORD: pass123
