version: "3"
services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/uploads

  db:
    image: "mariadb:10.4"
    environment:
      MYSQL_DATABASE: careers
      MYSQL_ROOT_PASSWORD: pass123
