version: "3"
services:
  api:
    build: .
    command: sh -c "python -m flask run --host=0.0.0.0"
    env_file:
      - ./envs/local.env
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/uploads

  db:
    image: "mariadb:10.4"
    restart: always
    environment:
      MYSQL_DATABASE: careers
      MYSQL_ROOT_PASSWORD: pass123
